deathbox:
  hologram-layout: "&c&l%player%&r deathbox\n&7despawn after:&r %timer%"
  duration: 10000 # -1 if forever
  unlock-after: 5000 # -1 to stay owner-only until despawn
  store-exp: true
  locked: true
  breakable: true

lifecycle:
  spawn:
    if-empty: false
    effect: ""
  land:
    effect: ""
  despawn:
    if-server-reloads: false
    if-empty: true
    drop-items: false
    effect: ""
  destroy:
    if-server-reloads: false
    drop-items: true
    effect: ""
